/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rug.eai.controlbus;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        assertTrue("Testing is important", true);
    }
}
